# Generated by Django 4.2.17 on 2026-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_category', models.CharField(choices=[('jewelry', 'Jewelry'), ('crochet', 'Crochet')], max_length=20)),
                ('sub_category', models.CharField(choices=[('watches', 'Watches'), ('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings'), ('anklets', 'Anklets'), ('brooches_pins', 'Brooches / Pins'), ('beanies', 'Beanies'), ('hats', 'Hats'), ('vests', 'Vests'), ('scarves', 'Scarves'), ('gloves_mittens', 'Gloves / Mittens'), ('headbands', 'Headbands'), ('bags', 'Bags'), ('shawls_wraps', 'Shawls / Wraps'), ('home_decor', 'Home Decor'), ('stuffed_toys', 'Stuffed Toys'), ('baby_items', 'Baby Items')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('colors_available', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['main_category', 'sub_category'], name='products_pr_main_ca_4c0c8f_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx')],
            },
        ),
    ]
